- name: Generate configuration file
  hosts: cisco
  vars:
    creds:
        host: "{{ host }}"
        username: "{{ username }}"
        password: "{{ password }}"
  tasks:
   - ios_config:
         match: exact
         provider: "{{ creds }}"
         lines:
           - permit ip host 3.3.3.3 any log
           - permit ip host 5.5.5.5 any log
           - permit ip host 2.2.2.2 any log
           - permit ip host 1.1.1.1 any log
           - permit ip host 4.4.4.4 any log
         parents: ['ip access-list extended acl1']
         before: ['no ip access-list extended acl1']
         replace: block
           
     notify: 
        - write mem

  handlers:
      - name: write mem
        ios_command:
          commands: "write mem"
          provider: "{{ creds }}"
        changed_when: True
