#!usr/bin/env python
import os

ip = raw_input("Enter a network address: ")
octets = ip.split(".")
print octets

for last_octet in range(1,11):
    octets[-1]=str(last_octet)
    #str_ip=str(octets)
    #print str_ip
    ping_ip = ".".join(octets)
    ping_cmd = "ping -c 1 -W 1 {} > /dev/null".format(ping_ip)
    status = os.system(ping_cmd)
    if status == 0:
        print "ping to ip: {} successful".format(ping_ip)
    else:
        print "ping to ip: {} failed".format(ping_ip)


